on:
  push:
    branches:
      gh-pages
      
name: Rebuild website

jobs:
  ping:
    name: Ping
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl -X POST -d '{}'  ${{ secrets.NETLIFY_HOOK }}
